// <auto-generated />
namespace Jewerly.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeattributes2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeattributes2));
        
        string IMigrationMetadata.Id
        {
            get { return "201603151628416_change attributes2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
